[package]
name = "crypto"
version = "0.1.0"
authors = ["MAP <developers@marcopolo.link>"]
edition = "2018"

[dependencies]
ed25519-dalek = "1.0.0-pre.3"
curve25519-dalek = "2"
blake2b-rs = "0.1.5"
blake2 = "0.8"
rand = "0.6.5"
rand_core = "0.5"
subtle = "2.2"
arrayref = "0.3"
digest = "0.8"
