[package]
name = "map-errors"
version = "0.1.0-pre"
license = "MIT"
authors = ["MAP <developers@maplabs.io>"]
edition = "2018"


[dependencies]
#log = "0.4.8"
failure = "0.1.7"
enum-display-derive = "0.1.0"
